config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: :index

  root 'timelogs#new'

  resources :projects

  resources :timelogs

  resources :keywords

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  # TODO: keywords borde ha synonymer

  has_and_belongs_to_many :timelogs

  validates :base, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :timelogs
  has_many :keywords, through: :timelogs

  validates :name, presence: true

end

app/models/timelog.rb
class Timelog < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  before_save :identify_keywords

  has_and_belongs_to_many :keywords

  validates :user,        presence: true
  validates :project,     presence: true
  validates :description, presence: true
  validates :start_time,  presence: true
  validates :duration,    presence: true,
                          numericality: {:greater_than => 0}

  def identify_keywords
    keywords = description.scan(/#\p{Word}+/).uniq.map { |kw| kw[1..-1] }

    keywords.each do |base|
      # TODO: stem base
      kw = Keyword.find_or_create_by(base: base)
      self.keywords << kw
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  respond_to :html,:json

  def index
    @keywords = Keyword.all.order(:base)
    respond_with(@keywords)
  end

  def show
    respond_with(@keyword)
  end

  def new
    @keyword = Keyword.new
    respond_with(@keyword)
  end

  def edit
  end

  def create
    @keyword = Keyword.new(keyword_params)
    @keyword.save
    respond_with(@keyword)
  end

  def update
    @keyword.update(keyword_params)
    respond_with(@keyword)
  end

  def destroy
    @keyword.destroy
    respond_with(@keyword)
  end

  private
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    def keyword_params
      params.require(:keyword).permit(:definition, :base)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.save
    respond_with(@project)
  end

  def update
    @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/timelogs_controller.rb
class TimelogsController < ApplicationController
  before_action :set_timelog, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @timelogs = Timelog.all
    respond_with(@timelogs)
  end

  def show
    respond_with(@timelog)
  end

  def new
    @timelog = Timelog.new
    respond_with(@timelog)
  end

  def edit
  end

  def create
    case params[:date_select]
    when "0"
      date = Date.yesterday
    when "1"
      date = Date.today
    when "2"
      date = params[:timelog][:date].to_date
    end
    params[:timelog][:start_time] = date
    params[:timelog][:user_id]  = current_user.id
    @timelog = Timelog.new(timelog_params)
    @timelog.save
    respond_with(@timelog)
  end

  def update
    @timelog.update(timelog_params)
    respond_with(@timelog)
  end

  def destroy
    @timelog.destroy
    respond_with(@timelog)
  end

  private
    def set_timelog
      @timelog = Timelog.find(params[:id])
    end

    def timelog_params
      params.require(:timelog).permit(:start_time, :duration, :description, :project_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    respond_to :json
    def index
        @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "notice" then "alert alert-info alert-dismissable"
      when "success" then "alert alert-success alert-dismissable"
      when "error" then "alert alert-danger"
      when "alert" then "alert alert-warning"
    end
  end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/timelogs_helper.rb
module TimelogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :definition %><br>
    <%= f.text_area :definition %>
  </div>
  <div class="field">
    <%= f.label :base %><br>
    <%= f.text_field :base %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<h1>Listing keywords</h1>
<textarea id="timelog_description"></textarea>
<table class="table">
  <thead>
    <tr>
      <th>Definition</th>
      <th>Base</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.definition %></td>
        <td><%= keyword.base %></td>
        <td><%= link_to 'Show', keyword %></td>
        <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
        <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Definition:</strong>
  <%= @keyword.definition %>
</p>

<p>
  <strong>Base:</strong>
  <%= @keyword.base %>
</p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fleskel</title>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% flash.each do |name, msg| %>
      <div class="<%= flash_class(name) %>">
        <%= msg %>
      </div>
    <% end %>

    <% if user_signed_in? %>
      <div class="container">
        <div class="col-xs-8 col-xs-offset-2">
          <div class="signed-in-user pull-right">
            Hej, <%= current_user.name %>
            <%= link_to "logga ut", destroy_user_session_path, method: :delete %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Project logged time comparasion</h1>
<%= pie_chart Project.all.map { |p| [p.name, p.timelogs.sum(:seconds)]} %>

<h1>Listing projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<h1>Project keywords logged time</h1>
<%= pie_chart Keyword.joins(:timelogs).where("timelogs.project_id=?",@project.id).group("keywords.id").sum(:seconds).map { |k, v| ["##{Keyword.find(k).base}",v]} %>

<h1>Project date logged time</h1>

<%= line_chart @project.timelogs.group_by_day(:start).sum(:seconds) %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/timelogs/_form.html.erb
<%= bootstrap_form_for(@timelog) do |f| %>
  <div class="row project-row">
    <div class="col-md-12">
      <%= f.text_field :project_id, append: content_tag(:span, "",class: "glyphicon glyphicon-chevron-right"), class: "biginput" %>
    </div>
  </div>

  <div class="row">
    <div class="timetabs" role="tabpanel">
      <ul class="nav nav-tabs" role="tablist">
        <li>
          <%= radio_button_tag :date_select, 0, false, hidden: true %>
          <label for="date_select_0">Igår</label>
        </li>
        <li>
          <%= radio_button_tag :date_select, 1, true, hidden: true %>
          <label for="date_select_1">Idag</label>
        </li>
        <li>
          <%= radio_button_tag :date_select, 2, false, hidden: true %>
          <label id="calendar-label" for="date_select_2">Kalender <span id="calendar-smalldate" class="hidden"></span></label>
        </li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="calendar-box collapsed" id="calendar-box">
      <div class="content">
        <div id="datepicker"></div>
        <%= f.hidden_field :date, value: Date.today %>
      </div>
    </div>
  </div>

  <div class="row timeselect-row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= f.number_field :duration %>
        </div>
      </div>
    </div>
  </div>

  <div class="row description-row">
    <div class="col-md-12">
      <%= f.text_area :description, class: "biginput"%>
      <%= f.submit "Spara", class: "btn btn-primary pull-right submit-btn" %>
    </div>
  </div>
<% end %>

app/views/timelogs/edit.html.erb
<h1>Editing timelog</h1>

<%= render 'form' %>

<%= link_to 'Show', @timelog %> |
<%= link_to 'Back', timelogs_path %>

app/views/timelogs/index.html.erb
<h1>Listing timelogs</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Start</th>
      <th>Seconds</th>
      <th>Description</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timelogs.each do |timelog| %>
      <tr>
        <td><%= timelog.user.name %></td>
        <td><%= timelog.start_time %></td>
        <td><%= timelog.duration %></td>
        <td><%= timelog.description %></td>
        <td><%= timelog.project.name %></td>
        <td><%= link_to 'Show', timelog %></td>
        <td><%= link_to 'Edit', edit_timelog_path(timelog) %></td>
        <td><%= link_to 'Destroy', timelog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timelog', new_timelog_path %>

app/views/timelogs/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 timelog-box">
    <%= render 'form' %>
  </div>
</div>

app/views/timelogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @timelog.user %>
</p>

<p>
  <strong>Start:</strong>
  <%= @timelog.start_time %>
</p>

<p>
  <strong>Seconds:</strong>
  <%= @timelog.duration %>
</p>

<p>
  <strong>Description:</strong>
  <%= @timelog.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @timelog.project %>
</p>

<%= link_to 'Edit', edit_timelog_path(@timelog) %> |
<%= link_to 'Back', timelogs_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name - Another branch?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>